### ISSUE TITLE
make contactUs page functional

### ISSUE THREAD

**Issue by sayyedarib** [sayyedarib/DonorLink#48]
either use emailjs in frontend or nodemailer in backend to send query to the mail "sayyedaribhussain4321@gmail.com"

**Comment by Tharuneshwarv** [comment]
Can u assign me this task

**Comment by sayyedarib** [comment]
let's do it😃

**Comment by Tharuneshwarv** [comment]
Fields required in the contact-us form?

**Comment by Tharuneshwarv** [comment]
@sayyedarib if your email id has 2 factor authentication. Then you need to create an app password for mail from google and replace it.

**Comment by sayyedarib** [comment]
it had added it while deploying to vercel
